[package]
name = "rs-vigor-policer"
version = "0.1.0"
authors = ["lucas <lucas.ramirez@epfl.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"

[lib]
crate-type = ["cdylib"]
